### ISSUE TITLE
Can't hide in debug screen

### ISSUE THREAD

**Issue by metaltube** [Shihyeon/ImagictHud#2]
The UI can't hide itself in any debug screens. e.g, F3 HUD.
Hope we can have a switch to turn it on/off. the designs are good, love its UI style.

**Comment by Shihyeon** [comment]
I'll add the ability to hide the hud when it's a debug overlay. The default is not to hide, but you can set it in the config.

**Comment by Shihyeon** [comment]
published
> https://modrinth.com/mod/imagict-hud/versions

ps. You can also disable the hud manually by pressing the `~` key.

**Comment by Shihyeon** [comment]
f4ccbe8ff7a887d43e0834b41d58cc953560b2fb
